### ISSUE TITLE
Scale invariant?

### ISSUE THREAD

**Issue by yoda0612** [AbhilashReddyM/curvpack#2]
Hi @AbhilashReddyM ,

I tried to use the curvature functions in your codes. Basically, I obtained what I need. However, I met a problem that if I scaled the 3D objects the curvature will be very different. Is there any method to deal with the scale invariant?
Thank you.

**Comment by AbhilashReddyM** [comment]
Hi @yoda0612 ,
Curvature is not dimensionless. it has units of length^-1. For example, a sphere of radius 'a' has curvature '2/a'. So if the radius changes the curvature will also change. This is what is supposed to happen.

**Comment by yoda0612** [comment]
Hi @AbhilashReddyM ,

Very appreciate for your response.
Actually, some one gave me a equation:  0.5 * Integrate 2*(Mean Curvature) will be the volume for a sphere. 
I am not sure if you know this relation.

**Comment by AbhilashReddyM** [comment]
no clue. see if this page helps. [Mass properties of solids represented by triangular surface mesh](https://abhilashreddy.com/writing/6/mesh_props.html). I am going to close this now.
